import { faker } from '@faker-js/faker';

import { BasicStatus, PermissionType } from '#/enum';

export const ORG_LIST = [
   {
      id: '1',
      name: 'East China Branch',
      status: 'enable',
      desc: faker.lorem.words(),
      order: 1,
      children: [
         { id: '1-1', name: 'R&D Department', status: 'disable', desc: '', order: 1 },
         { id: '1-2', name: 'Marketing Department', status: 'enable', desc: '', order: 2 },
         { id: '1-3', name: 'Finance Department', status: 'enable', desc: '', order: 3 },
      ],
   },
   {
      id: '2',
      name: 'South China Branch',
      status: 'enable',
      desc: faker.lorem.words(),
      order: 2,
      children: [
         { id: '2-1', name: 'R&D Department', status: 'disable', desc: '', order: 1 },
         { id: '2-2', name: 'Marketing Department', status: 'enable', desc: '', order: 2 },
         { id: '2-3', name: 'Finance Department', status: 'enable', desc: '', order: 3 },
      ],
   },
];
////

const DASHBOARD_PERMISSION = {
   id: '10001',
   parentId: '',
   label: 'sys.menu.dashboard.index',
   name: 'Dashboard',
   icon: 'ic-analysis',
   type: PermissionType.CATALOGUE,
   route: 'dashboard',
   order: 1,
   children: [
      {
         id: '100011',
         parentId: '10001',
         label: 'sys.menu.dashboard.workbench',
         name: 'Workbench',
         type: PermissionType.MENU,
         route: 'workbench',
         component: '/dashboard/workbench/index.tsx',
      },
      {
         id: '100012',
         parentId: '10001',
         label: 'sys.menu.dashboard.analysis',
         name: 'Analysis',
         type: PermissionType.MENU,
         route: 'analysis',
         component: '/dashboard/analysis/index.tsx',
      },
   ],
};
const MANAGEMENT_PERMISSION = {
   id: '10002',
   parentId: '',
   label: 'sys.menu.management.index',
   name: 'Management',
   icon: 'ic-management',
   type: PermissionType.CATALOGUE,
   route: 'management',
   order: 2,
   children: [
      {
         id: '100021',
         parentId: '10002',
         label: 'sys.menu.management.office',
         name: 'Office',
         type: PermissionType.MENU,
         route: 'office',
         component: '/management/office/index.tsx',
      },
      {
         id: '100022',
         parentId: '10002',
         label: 'sys.menu.management.vehicle',
         name: 'Vehicles',
         type: PermissionType.MENU,
         route: 'vehicle',
         component: '/management/vehicle/index.tsx',
      },
      {
         id: '100023',
         parentId: '10002',
         label: 'sys.menu.management.methodPayment',
         name: 'Methods Payment',
         type: PermissionType.MENU,
         route: 'method-payment',
         component: '/management/method-payment/index.tsx',
      },
      {
         id: '100024',
         parentId: '10002',
         label: 'sys.menu.management.driver',
         name: 'Driver',
         type: PermissionType.MENU,
         route: 'driver',
         component: '/management/driver/index.tsx',
      },
      {
         id: '100025',
         parentId: '10002',
         label: 'sys.menu.management.voucher',
         name: 'Voucher',
         type: PermissionType.MENU,
         route: 'voucher',
         component: '/management/voucher/index.tsx',
      },
      {
         id: '100026',
         parentId: '10002',
         label: 'sys.menu.management.review',
         name: 'Review',
         type: PermissionType.MENU,
         route: 'review',
         component: '/management/review/index.tsx',
      },
      {
         id: '100027',
         parentId: '10002',
         label: 'sys.menu.management.article',
         name: 'Article',
         type: PermissionType.MENU,
         route: 'article',
         component: '/management/article/index.tsx',
      },
   ],
};
const USERS_PERMISSION = {
   id: '10003',
   parentId: '',
   label: 'sys.menu.users.index',
   name: 'Users',
   icon: 'heroicons:user-group-solid',
   type: PermissionType.CATALOGUE,
   route: 'users',
   order: 3,
   children: [
      {
         id: '100031',
         parentId: '10003',
         label: 'sys.menu.users.customer',
         name: 'Customers',
         type: PermissionType.MENU,
         route: 'customer',
         component: '/users/customer/index.tsx',
      },
      {
         id: '100032',
         parentId: '10003',
         label: 'sys.menu.users.employee',
         name: 'Employee',
         type: PermissionType.MENU,
         route: 'employee',
         component: '/management/employee/index.tsx',
      },
      {
         id: '100033',
         parentId: '10003',
         label: 'sys.menu.users.permission.index',
         name: 'Permission',
         type: PermissionType.CATALOGUE,
         route: 'permission',
         children: [
            {
               id: '1000331',
               parentId: '100033',
               label: 'sys.menu.users.permission.role',
               name: 'Role',
               type: PermissionType.MENU,
               route: 'role',
               component: '/users/permission/role/index.tsx',
            },
            {
               id: '1000332',
               parentId: '100033',
               label: 'sys.menu.users.permission.group',
               name: 'Group',
               type: PermissionType.MENU,
               route: 'group',
               component: '/users/permission/group/index.tsx',
            },
            {
               id: '1000333',
               parentId: '100033',
               label: 'sys.menu.users.permission.grant-role',
               name: 'Grant Role',
               type: PermissionType.MENU,
               route: 'grant-role',
               component: '/users/permission/grant-role/index.tsx',
            },
         ],
      },
   ],
};
const ROUTES_PERMISSION = {
   id: '10004',
   parentId: '',
   label: 'sys.menu.routes.index',
   name: 'Routes',
   icon: 'gis:map-route',
   type: PermissionType.CATALOGUE,
   route: 'routes',
   order: 4,
   children: [
      {
         id: '100041',
         parentId: '10004',
         label: 'sys.menu.routes.route',
         name: 'Route',
         type: PermissionType.MENU,
         route: 'route',
         component: '/routes/route/index.tsx',
      },
      {
         id: '100042',
         parentId: '10004',
         label: 'sys.menu.routes.trip',
         name: 'Trip',
         type: PermissionType.MENU,
         route: 'trip',
         component: '/routes/trip/index.tsx',
      },
   ],
};
const REPORTS_PERMISSION = {
   id: '10005',
   parentId: '',
   label: 'sys.menu.reports.index',
   name: 'Reports',
   icon: 'mdi:report-areaspline',
   type: PermissionType.CATALOGUE,
   route: 'reports',
   order: 5,
   children: [
      {
         id: '100051',
         parentId: '10005',
         label: 'sys.menu.reports.customer',
         name: 'Customer',
         type: PermissionType.MENU,
         route: 'customer',
         component: '/reports/customer/index.tsx',
      },
      {
         id: '100052',
         parentId: '10005',
         label: 'sys.menu.reports.employee',
         name: 'Employee',
         type: PermissionType.MENU,
         route: 'employee',
         component: '/reports/employee/index.tsx',
      },
      {
         id: '100053',
         parentId: '10005',
         label: 'sys.menu.reports.by-employee',
         name: 'By Employee',
         type: PermissionType.MENU,
         route: 'by-employee',
         component: '/reports/by-employee/index.tsx',
      },
      {
         id: '100054',
         parentId: '10005',
         label: 'sys.menu.reports.booking',
         name: 'Booking',
         type: PermissionType.MENU,
         route: 'booking',
         component: '/reports/booking/index.tsx',
      },
      {
         id: '100055',
         parentId: '10005',
         label: 'sys.menu.reports.today',
         name: 'Today',
         type: PermissionType.MENU,
         route: 'today',
         component: '/reports/today/index.tsx',
      },
   ],
};
const SYSTEM_PERMISSION = {
   id: '10006',
   parentId: '',
   label: 'sys.menu.system.index',
   name: 'System',
   icon: 'solar:database-bold-duotone',
   type: PermissionType.CATALOGUE,
   route: 'system',
   order: 6,
   children: [
      {
         id: '100061',
         parentId: '10006',
         label: 'sys.menu.system.backup',
         name: 'Backup',
         type: PermissionType.MENU,
         route: 'backup',
         component: '/system/backup/index.tsx',
      },
      {
         id: '100062',
         parentId: '10006',
         label: 'sys.menu.system.restore',
         name: 'Restore',
         type: PermissionType.MENU,
         route: 'restore',
         component: '/system/restore/index.tsx',
      },
      {
         id: '100063',
         parentId: '10006',
         label: 'sys.menu.system.setting',
         name: 'Setting',
         type: PermissionType.MENU,
         route: 'setting',
         component: '/system/setting/index.tsx',
      },
   ],
};
const TICKETS_PERMISSION = {
   id: '10007',
   parentId: '',
   label: 'sys.menu.ticket.index',
   name: 'All Tickets',
   icon: 'dashicons:tickets-alt',
   type: PermissionType.MENU,
   newFeature: true,
   iconNewFeature: 'emojione:admission-tickets',
   route: 'ticket',
   order: 7,
   component: '/ticket/index.tsx',
};
const BOOKING_PERMISSION = {
   id: '10008',
   parentId: '',
   label: 'sys.menu.bookings.index',
   name: 'Bookings',
   icon: 'tabler:brand-booking',
   type: PermissionType.CATALOGUE,
   route: 'bookings',
   order: 8,
   children: [
      {
         id: '100081',
         parentId: '10008',
         label: 'sys.menu.bookings.booking',
         name: 'Booking',
         type: PermissionType.MENU,
         route: 'booking',
         component: '/bookings/booking/index.tsx',
      },
      {
         id: '100082',
         parentId: '10008',
         label: 'sys.menu.bookings.cancel',
         name: 'Cancel Ticket',
         type: PermissionType.MENU,
         route: 'cancel',
         component: '/bookings/cancel/index.tsx',
      },
      {
         id: '100083',
         parentId: '10008',
         label: 'sys.menu.bookings.history',
         name: 'History',
         type: PermissionType.MENU,
         route: 'history',
         component: '/bookings/history/index.tsx',
      },
   ],
};
const INFORMATION_PERMISSION = {
   id: '10009',
   parentId: '',
   label: 'sys.menu.information.index',
   name: 'Information',
   icon: 'fa-solid:user-edit',
   type: PermissionType.CATALOGUE,
   route: 'information',
   order: 9,
   children: [
      {
         id: '100091',
         parentId: '10009',
         label: 'sys.menu.information.profile',
         name: 'Profile',
         type: PermissionType.MENU,
         route: 'profile',
         component: '/information/profile/index.tsx',
      },
      {
         id: '100092',
         parentId: '10009',
         label: 'sys.menu.information.logout',
         name: 'Logout',
         type: PermissionType.MENU,
         route: 'logout',
         newFeature: true,
         iconNewFeature: 'uim:signout',
         component: '/information/logout/index.tsx',
      },
   ],
};

////

const COMPONENTS_PERMISSION = {
   id: '2271615060673773',
   parentId: '',
   label: 'sys.menu.components',
   name: 'Components',
   icon: 'solar:widget-5-bold-duotone',
   type: PermissionType.CATALOGUE,
   route: 'components',
   order: 3,
   children: [
      {
         id: '2478488238255411',
         parentId: '2271615060673773',
         label: 'sys.menu.icon',
         name: 'Icon',
         type: PermissionType.MENU,
         route: 'icon',
         component: '/components/icon/index.tsx',
      },
      {
         id: '6755238352318767',
         parentId: '2271615060673773',
         label: 'sys.menu.animate',
         name: 'Animate',
         type: PermissionType.MENU,
         route: 'animate',
         component: '/components/animate/index.tsx',
      },
      {
         id: '9992476513546805',
         parentId: '2271615060673773',
         label: 'sys.menu.scroll',
         name: 'Scroll',
         type: PermissionType.MENU,
         route: 'scroll',
         component: '/components/scroll/index.tsx',
      },
      {
         id: '1755562695856395',
         parentId: '2271615060673773',
         label: 'sys.menu.markdown',
         name: 'Markdown',
         type: PermissionType.MENU,
         route: 'markdown',
         component: '/components/markdown/index.tsx',
      },
      {
         id: '2122547769468069',
         parentId: '2271615060673773',
         label: 'sys.menu.editor',
         name: 'Editor',
         type: PermissionType.MENU,
         route: 'editor',
         component: '/components/editor/index.tsx',
      },
      {
         id: '2501920741714350',
         parentId: '2271615060673773',
         label: 'sys.menu.i18n',
         name: 'Multi Language',
         type: PermissionType.MENU,
         route: 'i18n',
         component: '/components/multi-language/index.tsx',
      },
      {
         id: '2013577074467956',
         parentId: '2271615060673773',
         label: 'sys.menu.upload',
         name: 'upload',
         type: PermissionType.MENU,
         route: 'Upload',
         component: '/components/upload/index.tsx',
      },
      {
         id: '7749726274771764',
         parentId: '2271615060673773',
         label: 'sys.menu.chart',
         name: 'Chart',
         type: PermissionType.MENU,
         route: 'chart',
         component: '/components/chart/index.tsx',
      },
   ],
};
const FUNCTIONS_PERMISSION = {
   id: '8132044808088488',
   parentId: '',
   label: 'sys.menu.functions',
   name: 'functions',
   icon: 'solar:plain-2-bold-duotone',
   type: PermissionType.CATALOGUE,
   route: 'functions',
   order: 4,
   children: [
      {
         id: '3667930780705750',
         parentId: '8132044808088488',
         label: 'sys.menu.clipboard',
         name: 'Clipboard',
         type: PermissionType.MENU,
         route: 'clipboard',
         component: '/functions/clipboard/index.tsx',
      },
      {
         id: '3667930780705751',
         parentId: '8132044808088488',
         label: 'sys.menu.token_expired',
         name: 'Token Expired',
         type: PermissionType.MENU,
         route: 'token-expired',
         component: '/functions/token-expired/index.tsx',
      },
   ],
};
const MENU_LEVEL_PERMISSION = {
   id: '0194818428516575',
   parentId: '',
   label: 'sys.menu.menulevel.index',
   name: 'Menu Level',
   icon: 'ic-menulevel',
   type: PermissionType.CATALOGUE,
   route: 'menu-level',
   order: 5,
   children: [
      {
         id: '0144431332471389',
         parentId: '0194818428516575',
         label: 'sys.menu.menulevel.1a',
         name: 'Menu Level 1a',
         type: PermissionType.MENU,
         route: 'menu-level-1a',
         component: '/menu-level/menu-level-1a/index.tsx',
      },
      {
         id: '7572529636800586',
         parentId: '0194818428516575',
         label: 'sys.menu.menulevel.1b.index',
         name: 'Menu Level 1b',
         type: PermissionType.CATALOGUE,
         route: 'menu-level-1b',
         children: [
            {
               id: '3653745576583237',
               parentId: '7572529636800586',
               label: 'sys.menu.menulevel.1b.2a',
               name: 'Menu Level 2a',
               type: PermissionType.MENU,
               route: 'menu-level-2a',
               component: '/menu-level/menu-level-1b/menu-level-2a/index.tsx',
            },
            {
               id: '4873136353891364',
               parentId: '7572529636800586',
               label: 'sys.menu.menulevel.1b.2b.index',
               name: 'Menu Level 2b',
               type: PermissionType.CATALOGUE,
               route: 'menu-level-2b',
               children: [
                  {
                     id: '4233029726998055',
                     parentId: '4873136353891364',
                     label: 'sys.menu.menulevel.1b.2b.3a',
                     name: 'Menu Level 3a',
                     type: PermissionType.MENU,
                     route: 'menu-level-3a',
                     component: '/menu-level/menu-level-1b/menu-level-2b/menu-level-3a/index.tsx',
                  },
                  {
                     id: '3298034742548454',
                     parentId: '4873136353891364',
                     label: 'sys.menu.menulevel.1b.2b.3b',
                     name: 'Menu Level 3b',
                     type: PermissionType.MENU,
                     route: 'menu-level-3b',
                     component: '/menu-level/menu-level-1b/menu-level-2b/menu-level-3b/index.tsx',
                  },
               ],
            },
         ],
      },
   ],
};
const ERRORS_PERMISSION = {
   id: '9406067785553476',
   parentId: '',
   label: 'sys.menu.error.index',
   name: 'Error',
   icon: 'bxs:error-alt',
   type: PermissionType.CATALOGUE,
   route: 'error',
   order: 6,
   children: [
      {
         id: '8557056851997154',
         parentId: '9406067785553476',
         label: 'sys.menu.error.403',
         name: '403',
         type: PermissionType.MENU,
         route: '403',
         component: '/sys/error/Page403.tsx',
      },
      {
         id: '5095669208159005',
         parentId: '9406067785553476',
         label: 'sys.menu.error.404',
         name: '404',
         type: PermissionType.MENU,
         route: '404',
         component: '/sys/error/Page404.tsx',
      },
      {
         id: '0225992135973772',
         parentId: '9406067785553476',
         label: 'sys.menu.error.500',
         name: '500',
         type: PermissionType.MENU,
         route: '500',
         component: '/sys/error/Page500.tsx',
      },
   ],
};
const OTHERS_PERMISSION = [
   {
      id: '3981225257359246',
      parentId: '',
      label: 'sys.menu.calendar',
      name: 'Calendar',
      icon: 'solar:calendar-bold-duotone',
      type: PermissionType.MENU,
      route: 'calendar',
      component: '/sys/others/calendar/index.tsx',
   },
   {
      id: '3513985683886393',
      parentId: '',
      label: 'sys.menu.kanban',
      name: 'kanban',
      icon: 'solar:clipboard-bold-duotone',
      type: PermissionType.MENU,
      route: 'kanban',
      component: '/sys/others/kanban/index.tsx',
   },
   {
      id: '5455837930804461',
      parentId: '',
      label: 'sys.menu.disabled',
      name: 'Disabled',
      icon: 'ic_disabled',
      type: PermissionType.MENU,
      route: 'disabled',
      status: BasicStatus.DISABLE,
      component: '/sys/others/calendar/index.tsx',
   },
   {
      id: '7728048658221587',
      parentId: '',
      label: 'sys.menu.label',
      name: 'Label',
      icon: 'ic_label',
      type: PermissionType.MENU,
      route: 'label',
      newFeature: true,
      component: '/sys/others/blank.tsx',
   },
   {
      id: '5733704222120995',
      parentId: '',
      label: 'sys.menu.frame',
      name: 'Frame',
      icon: 'ic_external',
      type: PermissionType.CATALOGUE,
      route: 'frame',
      children: [
         {
            id: '9884486809510480',
            parentId: '5733704222120995',
            label: 'sys.menu.external_link',
            name: 'External Link',
            type: PermissionType.MENU,
            route: 'external_link',
            hideTab: true,
            component: '/sys/others/iframe/external-link.tsx',
            frameSrc: 'https://ant.design/',
         },
         {
            id: '9299640886731819',
            parentId: '5733704222120995',
            label: 'sys.menu.iframe',
            name: 'Iframe',
            type: PermissionType.MENU,
            route: 'frame',
            component: '/sys/others/iframe/index.tsx',
            frameSrc: 'https://ant.design/',
         },
      ],
   },
   {
      id: '0941594969900756',
      parentId: '',
      label: 'sys.menu.blank',
      name: 'Disabled',
      icon: 'ic_blank',
      type: PermissionType.MENU,
      route: 'blank',
      component: '/sys/others/blank.tsx',
   },
];

export const PERMISSION_LIST = [
   DASHBOARD_PERMISSION,
   MANAGEMENT_PERMISSION,
   INFORMATION_PERMISSION,
   BOOKING_PERMISSION,
   TICKETS_PERMISSION,
   REPORTS_PERMISSION,
   SYSTEM_PERMISSION,
   ROUTES_PERMISSION,
   USERS_PERMISSION,
];

// export const PERMISSION_LIST = [
//    DASHBOARD_PERMISSION,
//    MANAGEMENT_PERMISSION,
//    COMPONENTS_PERMISSION,
//    FUNCTIONS_PERMISSION,
//    MENU_LEVEL_PERMISSION,
//    ERRORS_PERMISSION,
//    ...OTHERS_PERMISSION,
// ];

const ADMIN_ROLE = {
   id: '4281707933534332',
   name: 'Admin',
   label: 'admin',
   status: BasicStatus.ENABLE,
   order: 1,
   desc: 'Super Admin',
   permission: PERMISSION_LIST,
};
const TEST_ROLE = {
   id: '9931665660771476',
   name: 'Test',
   label: 'test',
   status: BasicStatus.ENABLE,
   order: 2,
   desc: 'test',
   permission: [DASHBOARD_PERMISSION, COMPONENTS_PERMISSION, FUNCTIONS_PERMISSION],
};

export const ROLE_LIST = [ADMIN_ROLE, TEST_ROLE];

export const DEFAULT_USER = {
   id: 'b34719e1-ce46-457e-9575-99505ecee828',
   username: 'admin',
   email: faker.internet.email(),
   avatar: faker.image.avatarGitHub(),
   createdAt: faker.date.anytime(),
   updatedAt: faker.date.recent(),
   password: 'demo1234',
   role: ADMIN_ROLE,
   permissions: ADMIN_ROLE.permission,
};
export const TEST_USER = {
   id: 'efaa20ea-4dc5-47ee-a200-8a899be29494',
   username: 'test',
   password: 'demo1234',
   email: faker.internet.email(),
   avatar: faker.image.avatarGitHub(),
   createdAt: faker.date.anytime(),
   updatedAt: faker.date.recent(),
   role: TEST_ROLE,
   permissions: TEST_ROLE.permission,
};

export const USER_LIST = [DEFAULT_USER, TEST_USER];
